import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useRouter from 'next/router'
import {useContext} from 'react'
import {AuthContext} from '../context/authContext'


const Home = (props) => {

  const {user,getUser} = useContext(AuthContext)

  console.log("user", user)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
    </div>
  )
}


export default Home